version: '3.8'

services:
  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"

  mongo-db:
    image: mongo:6.0
    ports:
      - "27017:27017"

  redis-service:
    image: redis:7.0
    ports:
      - "6379:6379"

  blockchain:
    image: trufflesuite/ganache-cli:latest
    platform: linux/amd64
    ports:
      - "8545:8545"
    command: ["-d"]