apiVersion: v1
kind: Secret
metadata:
  name: fond-secrets
type: Opaque
stringData:
  # Postgres kredencijali (auth-service + auth-db)
  POSTGRES_USER: auth_user
  POSTGRES_PASSWORD: auth_password
  # Zajednički JWT tajni ključ - MORA biti isti u sva tri Flask servisa
  JWT_SECRET_KEY: super-tajni-kljuc-promeni-ovo
